name: Generate Map Tiles

on:
  workflow_dispatch:

jobs:
  generate-tiles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow

      - name: Run generate_map_tiles.py
        run: python src/generate_map_tiles.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add map_data/
          git commit -m "Update map_data via GitHub Action" || echo "No changes to commit"
          git push